### PR TITLE
fix: TemplateExecutor fixed attributes

### LINKED ISSUE #35: TemplateMap ($map) Values Not Updating in TemplateExecutor
Currently, the `TemplateMap` used to provide key-value pairs in the `VelocityContext` (`$map` variable) is only set once per instance of the `TemplateExecutor` class. This design prevents updates to the `TemplateMap` from being reflected in the mapping, leading to stale or outdated values.

### PR DESCRIPTION
**Pull request by AuPath**
TemplateFunctions and TemplateMap should be provided for each mapping execution, as they could be changed (TemplateMap) or could contain stateful logic (TemplateFunctions). 

Closes #35, #36.

### CODE REVIEW

File: src/test/java/com/cefriel/template/MultipleReadersTest.java [hunk 1]
```diff
@@ -17,8 +17,8 @@ public void testMultipleReaders() throws Exception {
         Map<String, Reader> readers = Map.of("reader1", new CSVReader(new File("src/test/resources/multiple-readers/a.csv")),
                 "reader2", new CSVReader(new File("src/test/resources/multiple-readers/b.csv")));
         Path template = Paths.get("src/test/resources/multiple-readers/template.vm");
-        TemplateExecutor templateExecutor = new TemplateExecutor(new TemplateFunctions(), true, false, false, null, null);
-        String result = templateExecutor.executeMapping(readers, template).replaceAll("\\r\\n", "\n");;
+        TemplateExecutor templateExecutor = new TemplateExecutor( true, false, false, null);
+        String result = templateExecutor.executeMapping(readers, template, new TemplateFunctions(), null).replaceAll("\\r\\n", "\n");;
```
Comment (marioscrock) [inline src/test/java/com/cefriel/template/MultipleReadersTest.java:21]: I would keep a method .executeMapping(readers, template) that automatically calls .executeMapping(readers, template, new TemplateFunctions(), null) since in most of the cases only the default utils without a Map are used

**Review by marioscrock — CHANGES_REQUESTED** [review]

File: src/test/java/com/cefriel/template/MultipleReadersTest.java (hunk 1 above)
Comment (AuPath) [reply src/test/java/com/cefriel/template/MultipleReadersTest.java]: Adressed by [15327bb](https://github.com/cefriel/mapping-template/pull/37/commits/15327bb35f0e994ca99acbeb85cc56ae1b7dbb60).

**Review by marioscrock — APPROVED** [review]
